### ISSUE TITLE
Line Endings conversion

### ISSUE THREAD

**Issue by vuchl** [lublak/n8n-nodes-text-manipulation#1]
### Describe the function you would like to have

Hello  @lublak!

A feature I would like to see in the package ist conversion of line endings of binary files. Similar to Notepad++ where you can convert it in the status bar:
![image](https://user-images.githubusercontent.com/4921147/187670279-b8ff779e-4d2b-4706-8cdb-6586ea605277.png)

Cheers!

### Describe your current alternative solution.

Currently I use Notepad++ to convert the line endings after the fact.

**Comment by lublak** [comment]
Hi @vuchl :),

thanks for your feature request.
Currently the solution with regex does not work.
Would an option that special characters are allowed be enough?

![image](https://user-images.githubusercontent.com/44057030/187679531-2b1f6749-e4ae-4de9-bb6f-71656fc6da08.png)

**Comment by vuchl** [comment]
It's worth a try 👍

I tried like this but was not succesful:
![image](https://user-images.githubusercontent.com/4921147/187680084-1c4bbab1-144e-4d6c-b3b2-0bc6ace233ad.png)

or
![image](https://user-images.githubusercontent.com/4921147/187680205-d0e33a10-eb5f-4596-beed-e2049c132701.png)


hence the request

**Comment by lublak** [comment]
@vuchl I have said that you can not yet replace with special characters. It would be an option that I would like to implement. Was just as a question whether the option would be enough for you :).
This option would have just more options than only newlines.
Perhaps I expressed myself a bit poorly.
I will try to work on it this week.

**Comment by vuchl** [comment]
Was my fault. I got what I try to implemented but still wnated to share what I tried but you propably allready had a glimpse of that. Would love upgrade the package later and test it out 👍

Thanks for getting in touch so fast

**Comment by lublak** [comment]
@vuchl I implemented it today. But I haven't tested it yet if everything works as it should.
I will get to test it tomorrow so if everything works I can release it tomorrow :).

**Comment by vuchl** [comment]
Hey @lublak !

I updated the package via N8N. But the icon and functionality are still the same. I am not able to select the Replace Extended mode:
![image](https://user-images.githubusercontent.com/4921147/188111225-0aabea82-639a-4332-8a54-7bafeeeb310b.png)

Here the community node version:
![image](https://user-images.githubusercontent.com/4921147/188111344-0d7a97cf-f9f1-43be-a71b-62f636fdae75.png)

Any idea? Do I need to do something more to get the never node version?

Regards vuchl

**Comment by lublak** [comment]
@vuchl I just tried this on my site and it works as it should.
![grafik](https://user-images.githubusercontent.com/44057030/188112225-123ad61d-5fcb-40bd-9529-4f34e13c2a75.png)
Are you using Docker? Try restarting n8n.

**Comment by vuchl** [comment]
Restarting solved it 👍

**Comment by lublak** [comment]
@vuchl That's good I last read something along the lines that the automatic update doesn't quite work with docker. But I also assume that they are working on it :)

**Comment by vuchl** [comment]
interesting that installing works but updating not so much 🤷🏼‍♂️

My files now work like clockwork. Thanks man!

**Comment by lublak** [comment]
@vuchl cool :) if something happens again, you know where to find me! :D
