### ISSUE TITLE
Normalize Text

### ISSUE THREAD

**Issue by Zewb** [lublak/n8n-nodes-text-manipulation#10]
### Describe the function you would like to have

Hey guys! I love this node, and I was wondering how difficult would it be to basically add a normalize text option? And by that I mean take letters with diacritics like  â, ê, î, ô and change them to a, e, i, o, etc. In my particular use case we have a bit of old software that's used and it just completely breaks when it finds a letter with a diacritic. (Ironically, the system in question can have them inserted via their API...but it means the name will never be found because their own search can't find it.) 

Thank you again!

### Describe your current alternative solution.

I've been using the n8n Code block to do this manually, but having a drop in node to do it reliably would be fantastic!

**Comment by lublak** [comment]
@Zewb I think it will take a few days. In general, however, I would say that this function fits this node and I will add it.
Since there is already a function for this in Javascript, the whole thing is also quite simple.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize

**Comment by Zewb** [comment]
Awesome! Definitely let me know!

**Comment by lublak** [comment]
@Zewb hey :) i think this week i have time to look at it.
I'm currently thinking about where it would fit best.
I think it fits best under `replace -> predefined rule`. An alternative would be a completely new point.

**Comment by lublak** [comment]
@Zewb its implemented. You can try it in a few hours.
