### ISSUE TITLE
Please add a function that allows extracting text using regular expressions

### ISSUE THREAD

**Issue by mamadaevv** [lublak/n8n-nodes-text-manipulation#12]
### Describe the function you would like to have

I'm trying to use the "Replace with Regexp" function, but I need to find text, not replace it.

### Describe your current alternative solution.

Please add a function that allows extracting text using regular expressions.

**Comment by lublak** [comment]
It should work with group replacement 
`$1` is the first group `()`
![grafik](https://github.com/user-attachments/assets/1e0427d2-244e-4180-8e78-633ad70e2633)
