### ISSUE TITLE
Regex pattern info view doesn't show table

### ISSUE THREAD

**Issue by Rafurus** [lublak/n8n-nodes-text-manipulation#5]
### Describe the bug

Image showing regex pattern info:
![obraz](https://user-images.githubusercontent.com/12428720/200518253-52283722-ff0e-4417-a6f6-b70e7c32808d.png)

### Describe the expected behavior

There should be table or another way to show this data. 
It's very hard to read right now.

### What is your Node.js version?

17

### What is your n8n version?

0.200.0

### What is your n8n-nodes-text-manipulation version?

1.0.5

### What operating system are you seeing the problem on?

Linux

### Operating system version (or if other, then please fill in complete name and version)

Ubuntu 22.04

**Comment by lublak** [comment]
@Rafurus thanks for your report 😄 
Of course, this should not be so. Actually, it should be a table. I will have a look at it.

**Comment by lublak** [comment]
I think currently the best option is to disable the rule: `// eslint-disable-next-line n8n-nodes-base/node-param-description-unencoded-angle-brackets`

**Comment by lublak** [comment]
@Rafurus released in: 1.2.0
its not a perfect fix but it works
