### ISSUE TITLE
Percent-encoding from URL doesn't decode all characters

### ISSUE THREAD

**Issue by nealhead** [lublak/n8n-nodes-text-manipulation#7]
### Describe the bug

I am using the Read from JSON/Write to JSON option with Decode/Encode Entities and it is MOSTLY working and decodes most of the options but doesn't seem to work for reserve characters like %3A and %3F. I tried decoding again with another TextManipulation block to no avail. If there is a way for me to grab logs for this let me know how.

### Describe the expected behavior

I would expect all percent-encoded characters to be decoded.

### What is your Node.js version?

Unknown

### What is your n8n version?

1.4.1

### What is your n8n-nodes-text-manipulation version?

1.2.0

### What operating system are you seeing the problem on?

Linux

### Operating system version (or if other, then please fill in complete name and version)

Unraid 6.11.5

**Comment by lublak** [comment]
@nealhead hi. Thanks for the issue.
It is because decodeUri is used here.
I think this can be easily fixed and another decoding option offered for decodeUriComponent.
```
decodeURI('%3F%3A') => "%3F%3A"
decodeURIComponent('%3F%3A') => "?:"
```
I think I will publish something about it on Saturday.

**Comment by lublak** [comment]
@nealhead sry some private issues appear at the weekend. I will work on in the next week :/

**Comment by nealhead** [comment]
> @nealhead sry some private issues appear at the weekend. I will work on in the next week :/

No rush from my end, thank you for your awesome plugin. Personal life should always come first!

**Comment by lublak** [comment]
@nealhead Nevertheless, it's always problematic with my time :).
But thank you for your patience.

I fix it with this commit: https://github.com/lublak/n8n-nodes-text-manipulation/commit/5f8121f2f19a5726cf10c39c7e9f9dd8551d1905

Is it possible for you too test this?

**Comment by nealhead** [comment]
> @nealhead Nevertheless, it's always problematic with my time :). But thank you for your patience.
> 
> I fix it with this commit: [5f8121f](https://github.com/lublak/n8n-nodes-text-manipulation/commit/5f8121f2f19a5726cf10c39c7e9f9dd8551d1905)
> 
> Is it possible for you too test this?

I don't see a new release available

**Comment by lublak** [comment]
@nealhead sry my fault.
Of course, one should also publish a new version and not forget it.
It should be installable in a few minutes now.

**Comment by nealhead** [comment]
Looks like I have the same result.. Although I don't see "Url Component" under Decode/Encode Entities only Nothing, UrI, XML, HTML. Should there be another option for Url Component?

**Comment by lublak** [comment]
@nealhead yes it should :o do you update it?

![grafik](https://github.com/lublak/n8n-nodes-text-manipulation/assets/44057030/183e84e8-fec8-4117-85a1-cca4c3ec86ad)
![grafik](https://github.com/lublak/n8n-nodes-text-manipulation/assets/44057030/5204af3a-931b-4309-806b-7238a59339d8)

**Comment by nealhead** [comment]
I don't seem to have that option:
![image](https://github.com/lublak/n8n-nodes-text-manipulation/assets/121319/d08ccd7c-fddd-44f7-a8bc-6a6247ec832a)
And it appears to be up to date:
![image](https://github.com/lublak/n8n-nodes-text-manipulation/assets/121319/27c216b2-f61d-462b-900b-761510152383)

**Comment by lublak** [comment]
@nealhead ah i think you need to restart n8n. There was some issues about this (months ago don't know if they have fixed it yet)

**Comment by nealhead** [comment]
@lublak that did it! Thank you! The only thing I notice now is that + signs are still in place for spaces but I can fix that with a replace function. I'm not even sure if that is in spec for URI component.

**Comment by lublak** [comment]
> @lublak that did it! Thank you! The only thing I notice now is that + signs are still in place for spaces but I can fix that with a replace function. I'm not even sure if that is in spec for URI component.

Good to know! :) have fun with n8n!
