### ISSUE TITLE
Installing Produces Error on N8N version 1.11.1

### ISSUE THREAD

**Issue by bc24fl** [lublak/n8n-nodes-text-manipulation#8]
### Describe the bug

I'm running N8n version 1.11.1.  When trying to install the module via the GUI it produces the following error message:

Error installing new package

Error loading package "n8n-nodes-text-manipulation" :The specified package could not be loaded Cause: Cannot find module '/home/node/.n8n/nodes/node_modules/n8n-workflow/dist/src/index.js' 

### Describe the expected behavior

Should install without error.

### What is your Node.js version?

18.18.0

### What is your n8n version?

1.11.1

### What is your n8n-nodes-text-manipulation version?

1.3.0

### What operating system are you seeing the problem on?

Linux

### Operating system version (or if other, then please fill in complete name and version)

Using default N8n image

**Comment by lublak** [comment]
@bc24fl That looks very off.
n8n-workflow is the wrong path.
It looks more like a bug of your environment.
I will try it out myself with the latest version.

![grafik](https://github.com/lublak/n8n-nodes-text-manipulation/assets/44057030/77844821-7105-442e-b0cf-4ebe27167170)
