### ISSUE TITLE
Support Notion and Markdown

### ISSUE THREAD

**Issue by pooriaarab** [lublak/n8n-nodes-text-manipulation#9]
### Describe the function you would like to have

Can this node be updated to support notion and markdown features to? Like notion to markdown and vice versa

**Comment by lublak** [comment]
@pooriaarab First of all, notion is a platform and not a format? That wouldn't be a target here anyway.  This is only about text manipulation.
The same applies to markdown. It would be more of a structure than text.
So the function is not planned.

**Comment by lublak** [comment]
Not planned
